/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package henSeeJumpHigh;

/**
 *
 * @author vince
 */
public class GameFrame extends java.awt.Frame {

   /**
    * Creates new form GameFrame
    */
   public GameFrame() 
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the
    * form. WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      panel1 = new java.awt.Panel();
      button1 = new java.awt.Button();

      setMaximumSize(new java.awt.Dimension(700, 700));
      setMinimumSize(new java.awt.Dimension(700, 700));
      setPreferredSize(new java.awt.Dimension(700, 700));
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosing(java.awt.event.WindowEvent evt) {
            exitForm(evt);
         }
      });

      panel1.setBackground(new java.awt.Color(102, 204, 255));
      panel1.setMaximumSize(new java.awt.Dimension(700, 700));
      panel1.setMinimumSize(new java.awt.Dimension(700, 700));
      panel1.setPreferredSize(new java.awt.Dimension(700, 700));
      panel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 700, 5));

      button1.setLabel("button1");
      panel1.add(button1);

      add(panel1, java.awt.BorderLayout.CENTER);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * Exit the Application
    */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0);
    }//GEN-LAST:event_exitForm

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) 
   {
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new GameFrame().setVisible(true);
         }
      });
   }


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Button button1;
   private java.awt.Panel panel1;
   // End of variables declaration//GEN-END:variables
}
